# =======================================#
# -----------DUMBARTON THEME-------------#
# ----------------By: HENRI BIKOURI-------#
#-----------------https://henribikouri.github.io----#
#========================================#

# =======================================#
# -----------BASE SETTINGS---------------#
#========================================#

title: Henri Bikouri
email: henri.bikouri@enspy-uy1.cm
description: Ingénieur en génie informatique de l'École Polytechnique. Spécialisé en IA et Cloud.
keywords: Henri Bikouri, ingénieur informatique, génie logiciel, intelligence artificielle, cloud computing, portfolio développeur, ENSPY, Yaoundé
baseurl: ""                                      # the subpath of your site, e.g. /blog
url: "https://henribikouri.github.io"          # the base hostname & protocol for your site
image: /assets/img/croppeda.jpg               # used to generate site link preview
image_alt: Site web professionnel de Henri BIKOURI, ingénieur en génie informatique

# =======================================#
# -----------SITE SETTINGS---------------#
#========================================#
author: Henri Bikouri
profile_image: /assets/img/avatar/cropped.jpg
occupation: Ingénieur Informatique
snippet: Spécialisé en IA, génie logiciel et cloud computing
twitter: hbikouri
github: Henribikouri
github_repository: Henribikouri.github.io
# Lien nettoyé pour faire professionnel :
linkedin: https://www.linkedin.com/in/henri-bikouri-bi-bep-a14463281
stackoverflow: 
website: 
codepen: 
medium: 
keybase: 
pgp: 
ctftime: 
phonenumber: 


defaults:
  - scope:
      path: "googleadd7935b089b3ccc.html"
    values:
      sitemap: false

#========================================#
# --------- UI THEMES -------------------#
#========================================#
ui_theme: abyss                                 # Create your own theme by setting options in _data/themes.yml


# =======================================#
# -----------BLOG SETTINGS---------------#
#========================================#

# tags: post henri  <-- COMMENTÉ (Mieux vaut définir les tags dans chaque article)
twitter-widget: false # true,false                  # Used to show your twitter timeline on blog home page

comments: false                                     # Used to enable comments on blog posts
gitalk_client_id:             
gitalk_client_secret:    
gitalk_repo:
gitalk_owner: 
gitalk_admin: 
gitalk_distraction_mode: false

# =======================================#
# -----------THEME SETTINGS--------------#
#========================================#

nav-color: "#00334e"                                 # options: light, dark, transparent, primary, custom | Change the color of the navbar
footer-color: "#00334e"
color-scheme: "#00334e"                              # options: demo | changes color scheme based on preset values 
card-color: "#00334e"                                # Used on cards like the home highlights section
nav-dIcon: "fas fa-caret-down"                       # Change the navbar dropdown 
animate: false                                      # false or true, uses animate.css to animate certain functions

# =======================================#
# -----------HOME PAGE  SETTINGS --------#
#========================================#
home_option: education                               # options: education, skills, timeline

# =======================================#          # These  settings are for demo purposes only
# -----------HELP SETTINGS---------------#          
#========================================#           
help_tips: false                                    # options: true, false  | use false to disable these for production mode


# =======================================#
# -----------BUILD SETTINGS--------------#
#========================================#
theme: 
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-environment-variables
  - jekyll-seo-tag
  - jekyll-sitemap # <--- TRES IMPORTANT : Cela génère votre sitemap.xml pour Google !

sass:
  sass_dir: _sass
  style: compressed


include:
  - _posts

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# =======================================#
# -----JEKYLL SCHOLAR SETTINGS-----------#
#========================================#
scholar:
  last_name: Henri
  style: apa
  locale: fr
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: 
  query: "@*"

# =======================================#
# ------------CDN SETTINGS---------------#
#-------------Used to generate icons-----#
#========================================#
# font_awesome_id: 32a2b2a489                       # COMMENTÉ : On utilise la version locale pour la vitesse (MTN)


# =======================================#        # For more information about these settings, visit https://htmlhead.dev #
# ------------META TAG SETTINGS----------#
#========================================#
google-site-verification: ORoUFOJqxXbH2OLpliZMDAx_Wtb3qt7BNZ4lmfW-K8U                       #<meta name="google-site-verification" content="verification_token">yandex-verification:                                  #<meta name="yandex-verification" content="verification_token">msvalidate:                                           # meta name="msvalidate.01" content="verification_token">alexaVerifyID:                                        # <meta name="alexaVerifyID" content="verification_token">pinterestdomain_verify:                               #<meta name="p:domain_verify" content="code_from_pinterest">norton-safeweb:                                       # <meta name="norton-safeweb-site-verification" content="norton_code">detectphone: yes                                      # yes or no. Disable automatic detection and formatting of possible phone numbers 
x-dns-prefetch-control: on                            # on or off. Completely opt out of DNS prefetching by setting to "off"
fbappid:                                              # Facebook OpenGraph